import React, { useState, useMemo } from 'react';
import {
  CheckSquare,
  Square,
  Plus,
  Trash2,
  Calendar,
  Clock,
  AlertCircle,
  Filter,
  Sparkles,
  Droplets,
  Bug,
  Sprout,
  Beef,
  Layers,
  ChevronRight,
  CheckCircle2,
  Bell,
  RefreshCw
} from 'lucide-react';
import { CommodityId, FarmerDailyTask, TaskCategory, TaskPriority } from '../types';
import { getDailyTasks, addDailyTask, toggleDailyTask, deleteDailyTask, addNotification } from '../utils/offlineStorage';
import { COMMODITIES } from '../utils/calculatorEngine';
import { CROP_SCHEDULES } from '../data/cropSchedules';

interface FarmerDailyTasksModuleProps {
  initialCommodityId?: CommodityId;
}

export const FarmerDailyTasksModule: React.FC<FarmerDailyTasksModuleProps> = ({
  initialCommodityId = 'padi'
}) => {
  const [tasks, setTasks] = useState<FarmerDailyTask[]>(() => getDailyTasks());
  const [activeFilter, setActiveFilter] = useState<'hari_ini' | 'semua' | 'pending' | 'selesai'>('hari_ini');
  const [selectedCommodity, setSelectedCommodity] = useState<CommodityId>(initialCommodityId);
  const [showAddModal, setShowAddModal] = useState<boolean>(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  // Form state for adding new task
  const [formTitle, setFormTitle] = useState<string>('');
  const [formCategory, setFormCategory] = useState<TaskCategory>('penyiraman');
  const [formDueDate, setFormDueDate] = useState<string>(() => new Date().toISOString().split('T')[0]);
  const [formDueTime, setFormDueTime] = useState<string>('07:00');
  const [formPriority, setFormPriority] = useState<TaskPriority>('sedang');
  const [formNotes, setFormNotes] = useState<string>('');

  const todayStr = new Date().toISOString().split('T')[0];

  const triggerToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  const filteredTasks = useMemo(() => {
    return tasks.filter(task => {
      if (activeFilter === 'hari_ini') return task.dueDate === todayStr;
      if (activeFilter === 'pending') return !task.isCompleted;
      if (activeFilter === 'selesai') return task.isCompleted;
      return true;
    });
  }, [tasks, activeFilter, todayStr]);

  const stats = useMemo(() => {
    const total = tasks.length;
    const completed = tasks.filter(t => t.isCompleted).length;
    const dueToday = tasks.filter(t => t.dueDate === todayStr).length;
    const pendingToday = tasks.filter(t => t.dueDate === todayStr && !t.isCompleted).length;
    const percent = total > 0 ? Math.round((completed / total) * 100) : 0;
    return { total, completed, dueToday, pendingToday, percent };
  }, [tasks, todayStr]);

  const handleToggle = (id: string, title: string) => {
    const updated = toggleDailyTask(id);
    setTasks(updated);
    const toggled = updated.find(t => t.id === id);
    if (toggled?.isCompleted) {
      triggerToast(`Tugas "${title}" berhasil diselesaikan! 🎉`);
    }
  };

  const handleDelete = (id: string) => {
    if (confirm('Hapus tugas harian ini?')) {
      const updated = deleteDailyTask(id);
      setTasks(updated);
      triggerToast('Tugas dihapus.');
    }
  };

  const handleCreateTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formTitle.trim()) return;

    const newTask = addDailyTask({
      title: formTitle,
      category: formCategory,
      commodityId: selectedCommodity,
      dueDate: formDueDate,
      dueTime: formDueTime,
      priority: formPriority,
      notes: formNotes,
      isAutoGenerated: false
    });

    const updated = getDailyTasks();
    setTasks(updated);
    setShowAddModal(false);

    // Reset
    setFormTitle('');
    setFormNotes('');

    addNotification({
      title: '📋 Tugas Harian Baru Ditambahkan',
      message: `Tugas "${newTask.title}" dijadwalkan pada ${newTask.dueDate} jam ${newTask.dueTime}.`,
      type: 'jadwal',
      priority: 'normal'
    });

    triggerToast('Tugas baru berhasil disimpan!');
  };

  // Sync / Import tasks automatically from Crop Schedule
  const handleAutoSyncFromSchedule = () => {
    const schedule = CROP_SCHEDULES[selectedCommodity];
    if (!schedule) return;

    let addedCount = 0;
    const existingTitles = new Set(tasks.map(t => t.title));

    // Map schedule items to daily tasks
    schedule.schedules.forEach((item, idx) => {
      const taskTitle = `${item.title} (HST ${item.dayAfterPlanting})`;
      if (!existingTitles.has(taskTitle)) {
        // Calculate due date relative to today + idx days
        const d = new Date();
        d.setDate(d.getDate() + Math.min(30, idx * 5));
        const dueDate = d.toISOString().split('T')[0];

        addDailyTask({
          title: taskTitle,
          category: item.actionType.toLowerCase().includes('kocor') || item.actionType.toLowerCase().includes('semprot') ? 'pemupukan' : 'pengolahan_tanah',
          commodityId: selectedCommodity,
          dueDate,
          dueTime: '06:45',
          priority: 'tinggi',
          notes: `${item.mixingInstruction} • Dosis: ${item.dosage}. Sasaran: ${item.targetStomata}.`,
          isAutoGenerated: true,
          sourceScheduleItemTitle: item.title
        });
        addedCount++;
      }
    });

    const updated = getDailyTasks();
    setTasks(updated);
    triggerToast(`Berhasil menarik ${addedCount} tugas otomatis dari jadwal ${COMMODITIES[selectedCommodity]?.name || 'komoditas'}!`);
  };

  const getCategoryIcon = (cat: TaskCategory) => {
    switch (cat) {
      case 'penyiraman':
        return <Droplets className="w-4 h-4 text-blue-500" />;
      case 'pengecekan_hama':
        return <Bug className="w-4 h-4 text-rose-500" />;
      case 'pemupukan':
        return <Sprout className="w-4 h-4 text-emerald-500" />;
      case 'pengolahan_tanah':
        return <Layers className="w-4 h-4 text-amber-500" />;
      case 'pakan_ternak':
        return <Beef className="w-4 h-4 text-purple-500" />;
      default:
        return <CheckSquare className="w-4 h-4 text-slate-500" />;
    }
  };

  return (
    <div className="space-y-4">
      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed top-16 left-1/2 -translate-x-1/2 z-50 bg-slate-900/95 dark:bg-emerald-950/95 text-white text-xs font-semibold px-4 py-2 rounded-full shadow-lg backdrop-blur-md animate-in fade-in duration-200 border border-emerald-500 flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-emerald-400" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Header Card */}
      <div className="bg-gradient-to-r from-emerald-900 via-teal-900 to-emerald-800 text-white rounded-3xl p-4 sm:p-6 shadow-md relative overflow-hidden">
        <div className="relative z-10 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-white/15 text-emerald-200 text-xs font-bold mb-2">
              <CheckSquare className="w-3.5 h-3.5 text-amber-300" />
              <span>Agenda Lapangan & Checklist Perawatan</span>
            </div>
            <h3 className="text-xl sm:text-2xl font-black font-['Outfit'] tracking-tight">
              Tugas Harian Petani
            </h3>
            <p className="text-xs sm:text-sm text-emerald-100 mt-1 max-w-xl">
              Catat kegiatan penyiraman, pengecekan hama/gulma, dan pemupukan Paten dengan pengingat otomatis dari jadwal tanam.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2 self-start sm:self-auto">
            <button
              type="button"
              onClick={handleAutoSyncFromSchedule}
              className="px-3 py-1.5 rounded-xl bg-white/15 hover:bg-white/25 text-white border border-white/20 text-xs font-bold flex items-center gap-1.5 transition-colors shadow-2xs backdrop-blur-md"
              title="Tarik rekomendasi tahapan HST dari jadwal tanam resmi"
            >
              <RefreshCw className="w-3.5 h-3.5 text-amber-300" />
              <span>Tarik dari Jadwal Tanam</span>
            </button>

            <button
              type="button"
              onClick={() => setShowAddModal(true)}
              className="px-3.5 py-1.5 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-black text-xs flex items-center gap-1.5 transition-colors shadow-sm"
            >
              <Plus className="w-4 h-4" />
              <span>Tambah Tugas</span>
            </button>
          </div>
        </div>

        {/* Mini progress stats bar */}
        <div className="mt-4 pt-3 border-t border-white/15 grid grid-cols-3 gap-2 text-center text-xs">
          <div className="bg-black/20 rounded-xl p-2">
            <span className="text-[10px] text-emerald-200 block uppercase font-bold">Hari Ini:</span>
            <span className="text-base font-black text-white">{stats.dueToday} Tugas</span>
          </div>
          <div className="bg-black/20 rounded-xl p-2">
            <span className="text-[10px] text-emerald-200 block uppercase font-bold">Belum Selesai:</span>
            <span className="text-base font-black text-amber-300">{stats.pendingToday} Tugas</span>
          </div>
          <div className="bg-black/20 rounded-xl p-2">
            <span className="text-[10px] text-emerald-200 block uppercase font-bold">Progres Checklist:</span>
            <span className="text-base font-black text-emerald-400">{stats.percent}% Selesai</span>
          </div>
        </div>
      </div>

      {/* Filter Tabs & Commodity Selector */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl p-3 border border-slate-200 dark:border-slate-800 shadow-xs flex flex-col sm:flex-row items-center justify-between gap-2.5">
        <div className="flex items-center gap-1.5 overflow-x-auto w-full sm:w-auto text-xs">
          {[
            { id: 'hari_ini' as const, label: '📅 Hari Ini' },
            { id: 'pending' as const, label: '⏳ Belum Selesai' },
            { id: 'selesai' as const, label: '✅ Selesai' },
            { id: 'semua' as const, label: 'Semua Tugas' }
          ].map(f => (
            <button
              key={f.id}
              onClick={() => setActiveFilter(f.id)}
              className={`px-3 py-1.5 rounded-xl font-bold whitespace-nowrap transition-colors border ${
                activeFilter === f.id
                  ? 'bg-emerald-700 text-white border-emerald-700 shadow-2xs'
                  : 'bg-slate-50 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-700'
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>

        <div className="flex items-center gap-1.5 w-full sm:w-auto justify-end text-xs">
          <span className="text-slate-500 dark:text-slate-400 font-bold whitespace-nowrap">Komoditi:</span>
          <select
            value={selectedCommodity}
            onChange={(e) => setSelectedCommodity(e.target.value as CommodityId)}
            className="bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl px-2.5 py-1.5 text-xs text-slate-800 dark:text-slate-200 font-semibold"
          >
            {Object.values(COMMODITIES).map(c => (
              <option key={c.id} value={c.id}>{c.icon} {c.name.split('(')[0]}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Task List Items */}
      <div className="space-y-2.5">
        {filteredTasks.length === 0 ? (
          <div className="bg-white dark:bg-slate-900 rounded-2xl p-8 text-center border border-slate-200 dark:border-slate-800 space-y-2">
            <CheckCircle2 className="w-10 h-10 text-emerald-500 mx-auto" />
            <h4 className="text-sm font-extrabold text-slate-800 dark:text-slate-200">
              Tidak Ada Tugas untuk Kategori Ini
            </h4>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Lahan dan jadwal Anda terkendali dengan baik. Klik "Tambah Tugas" untuk membuat catatan baru.
            </p>
          </div>
        ) : (
          filteredTasks.map((task) => {
            const isToday = task.dueDate === todayStr;
            return (
              <div
                key={task.id}
                className={`p-3.5 rounded-2xl border transition-all flex items-start justify-between gap-3 ${
                  task.isCompleted
                    ? 'bg-slate-50/80 dark:bg-slate-900/60 border-slate-200 dark:border-slate-800 opacity-75'
                    : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 hover:border-emerald-300 dark:hover:border-emerald-800 shadow-2xs'
                }`}
              >
                <div className="flex items-start gap-3 min-w-0">
                  <button
                    type="button"
                    onClick={() => handleToggle(task.id, task.title)}
                    className="mt-0.5 text-emerald-600 dark:text-emerald-400 hover:scale-110 transition-transform shrink-0"
                    title={task.isCompleted ? 'Tandai belum selesai' : 'Tandai selesai'}
                  >
                    {task.isCompleted ? (
                      <CheckSquare className="w-5 h-5 fill-emerald-600 dark:fill-emerald-400 text-white" />
                    ) : (
                      <Square className="w-5 h-5 text-slate-400 dark:text-slate-600" />
                    )}
                  </button>

                  <div className="min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className={`text-xs font-extrabold font-['Outfit'] ${
                        task.isCompleted
                          ? 'line-through text-slate-500 dark:text-slate-400'
                          : 'text-slate-900 dark:text-slate-100'
                      }`}>
                        {task.title}
                      </span>

                      {task.priority === 'tinggi' && (
                        <span className="px-1.5 py-0.2 rounded-md bg-rose-100 dark:bg-rose-950/80 text-rose-700 dark:text-rose-300 text-[9px] font-extrabold border border-rose-300 dark:border-rose-800">
                          Prioritas Tinggi
                        </span>
                      )}

                      {task.isAutoGenerated && (
                        <span className="px-1.5 py-0.2 rounded-md bg-amber-100 dark:bg-amber-950/80 text-amber-800 dark:text-amber-300 text-[9px] font-extrabold border border-amber-300 dark:border-amber-800">
                          Jadwal HST
                        </span>
                      )}
                    </div>

                    {task.notes && (
                      <p className="text-[11px] text-slate-600 dark:text-slate-300 mt-1 leading-relaxed">
                        {task.notes}
                      </p>
                    )}

                    <div className="flex items-center gap-3 mt-2 text-[10px] text-slate-500 dark:text-slate-400 flex-wrap">
                      <span className="flex items-center gap-1 font-semibold">
                        {getCategoryIcon(task.category)}
                        <span className="capitalize">{task.category.replace('_', ' ')}</span>
                      </span>

                      <span className="flex items-center gap-1 font-mono">
                        <Calendar className="w-3 h-3" />
                        <span>{task.dueDate}</span>
                      </span>

                      {task.dueTime && (
                        <span className="flex items-center gap-1 font-mono">
                          <Clock className="w-3 h-3" />
                          <span>{task.dueTime}</span>
                        </span>
                      )}

                      {task.isCompleted && task.completedAt && (
                        <span className="text-emerald-600 dark:text-emerald-400 font-bold">
                          ✓ Selesai jam {task.completedAt}
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => handleDelete(task.id)}
                  className="p-1 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-slate-800 transition-colors shrink-0"
                  title="Hapus tugas"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            );
          })
        )}
      </div>

      {/* Modal Add Task */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-3 sm:p-5">
          <div className="bg-white dark:bg-slate-900 rounded-3xl max-w-md w-full p-5 space-y-4 shadow-2xl border border-slate-200 dark:border-slate-800 animate-in zoom-in-95 duration-200">
            <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
              <h4 className="text-sm sm:text-base font-extrabold text-slate-900 dark:text-slate-100 font-['Outfit']">
                Tambah Catatan Tugas Harian
              </h4>
              <button
                onClick={() => setShowAddModal(false)}
                className="p-1 text-slate-400 hover:text-slate-700 dark:hover:text-slate-200"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleCreateTask} className="space-y-3 text-xs">
              <div>
                <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Kegiatan / Tugas</label>
                <input
                  type="text"
                  required
                  placeholder="Contoh: Semprot Paten Imun pencegahan blas daun"
                  value={formTitle}
                  onChange={(e) => setFormTitle(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl px-3 py-2 text-slate-800 dark:text-slate-100 font-semibold"
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Kategori</label>
                  <select
                    value={formCategory}
                    onChange={(e) => setFormCategory(e.target.value as TaskCategory)}
                    className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl px-2.5 py-2 text-slate-800 dark:text-slate-100"
                  >
                    <option value="penyiraman">💧 Penyiraman</option>
                    <option value="pengecekan_hama">🐛 Cek Hama/Gulma</option>
                    <option value="pemupukan">🌱 Pemupukan Paten</option>
                    <option value="pengolahan_tanah">🚜 Olah Tanah</option>
                    <option value="pakan_ternak">🐂 Pakan Ternak</option>
                    <option value="panen">🌾 Pemanenan</option>
                    <option value="lainnya">📝 Lainnya</option>
                  </select>
                </div>

                <div>
                  <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Prioritas</label>
                  <select
                    value={formPriority}
                    onChange={(e) => setFormPriority(e.target.value as TaskPriority)}
                    className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl px-2.5 py-2 text-slate-800 dark:text-slate-100"
                  >
                    <option value="tinggi">🔴 Tinggi (Segera)</option>
                    <option value="sedang">🟡 Sedang</option>
                    <option value="rendah">🟢 Rendah</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Tanggal</label>
                  <input
                    type="date"
                    required
                    value={formDueDate}
                    onChange={(e) => setFormDueDate(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl px-2.5 py-2 text-slate-800 dark:text-slate-100"
                  />
                </div>

                <div>
                  <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Waktu</label>
                  <input
                    type="time"
                    value={formDueTime}
                    onChange={(e) => setFormDueTime(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl px-2.5 py-2 text-slate-800 dark:text-slate-100 font-mono"
                  />
                </div>
              </div>

              <div>
                <label className="block font-bold text-slate-700 dark:text-slate-300 mb-1">Catatan / Takaran</label>
                <textarea
                  rows={2}
                  placeholder="Contoh: Larutkan 1 sachet per tangki, semprot bagian bawah daun."
                  value={formNotes}
                  onChange={(e) => setFormNotes(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl px-3 py-2 text-slate-800 dark:text-slate-100"
                />
              </div>

              <div className="flex justify-end gap-2 pt-2 border-t border-slate-100 dark:border-slate-800">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="px-4 py-2 rounded-xl border border-slate-300 dark:border-slate-700 text-slate-700 dark:text-slate-300 font-bold"
                >
                  Batal
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 rounded-xl bg-emerald-700 hover:bg-emerald-800 text-white font-bold transition-colors"
                >
                  Simpan Tugas
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
